baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Telephone support line 10am-4pm Monday-Friday: 0488 199 129'
theme = 'ananke'
canonifyURLs = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'